# Generated by Django 4.2.4 on 2023-08-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=240, verbose_name='Brand')),
                ('model', models.CharField(max_length=240, verbose_name='Model')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'IHA0'), (1, 'IHA1'), (2, 'IHA2'), (3, 'IHA3')], null=True)),
            ],
        ),
    ]
